### ISSUE TITLE
NullPointerException when setting credentials

### ISSUE THREAD

**Issue by Rubyj** [crukci-bioinformatics/clarityclient#5]
Hello,

I am trying to use your Java client and am having an issue when I try to set the credentials. There wasn't any documentation to refer to, so this is what I came up with.

```
      clarityUrl = new URL(CLARITY_URL);
      UsernamePasswordCredentials clarityCredentials = new UsernamePasswordCredentials(CLARITY_USER, CLARITY_PW);
      HttpComponentsClientHttpRequestFactoryBasicAuth requestFactory = new HttpComponentsClientHttpRequestFactoryBasicAuth();
      api.setHttpRequestFactory(requestFactory);
      api.setServer(clarityUrl);
      api.setCredentials(clarityCredentials);
```

On the setCredentials() method, I encounter a NullPointerException with the message "null null". The username and password are indeed correct strings. Am I doing something wrong here? Thank you.

**Comment by rich7409** [comment]
Hi. It's difficult to know without the stack trace and the wider code. The HTTP request factory should be wired in by Spring. How are you getting hold of the API implementation? You need to fetch it from Spring's application context. If you're not doing that and are just calling new GenologicsAPIImpl(); none of its dependencies will be injected.

The instructions for getting the API implementation are in the documentation: http://crukci-bioinformatics.github.io/clarityclient/spring.html

Rich.

**Comment by Rubyj** [comment]
Hi Rich,

Thanks for your input. I was indeed using new GenologicsAPIImpl(); So, just to clarify, this Java client will only work in the context of an existing Spring application?

Thanks,
Reuben

**Comment by rich7409** [comment]
Hi. Not necessarily, but you will have to introduce Spring into your application if it's not there. You can use it to get the Clarity client but otherwise ignore it.

**Comment by Rubyj** [comment]
I see. I will try that then. Thank you!
