### ISSUE TITLE
Where is version 2.25 of the API?

### ISSUE THREAD

**Issue by gaviriar** [crukci-bioinformatics/clarityclient#6]
Hi There, I see the [README.md](https://github.com/KariusDx/clarity-client#clarity-5) seems to be referencing a version 2.25 of the API however I do not see the corresponding tag on the repo or any reference of version 2.25 anywhere in the code. Do you mind pointing me to which commit it is? As I would like to test this API on a Clarity 5 LIMS.

Thanks in advance for the help.

**Comment by rich7409** [comment]
Hi. I don't think I got round to making a formal tag of 2.25, nor have I moved the code up to 2.26 yet (Clarity 5.1). The head of the master branch as is would be the 2.25.0 release, except for POM versions.

We've been very busy with the NovaSeq integration these last four weeks but that's done now so I'll find some time to tag 2.25.0 and make the changes for 2.26 from the XML files. We are at a disadvantage here as we're on Clarity 4.2 and will be for at least another year until 5.2 comes out with its Lablink and Operations replacements (before Clarity is then binned by Illumina - not happy about that at all!).

I'll tag a 2.25.0 release today.

Rich.

**Comment by gaviriar** [comment]
Hi Rich,

Thanks for your response and clarifications. I will work on top of `master` branch then. I will need to interact with Clarity 5.1 version.

**What changes are required for 5.1 support?** I could then do some implementation and testing and leave the review for you on a merge request?

Wait what? Clarity is getting binned by Illumina? 

--
Ricardo

**Comment by rich7409** [comment]
Outside of automation and demultiplexing artifacts there are minimal changes. You might get a problem with the file elements, as there is now an "original name" element. Otherwise I think you will be ok with the 5.0/2.25 version to start with.

**Comment by rich7409** [comment]
And yes, Illumina are planning for Clarity 5.2 (Q3 2019) to be the last release. This is what they sent us in March:

> We are committed to creating an end-to-end sequencing solution that helps customers manage all aspects of a sample’s life cycle, from sample acquisition to data analysis and to interpretation of results. This end-to-end sequencing solution will include a tightly integrated informatics platform that will be developed in tandem with new sequencers and flow cell technology to provide an improved overall sequencing experience.  To accelerate the development of the end-to-end sequencing solution, we will move away from the stand-alone BaseSpace Clarity LIMS product, and we will migrate some of the key capabilities of Clarity LIMS into the Illumina core informatics platform.  To accomplish this, and to better support our existing LIMS customers, we have decided to reduce the scope of the stand-alone Clarity LIMS roadmap by:

-     Released NovaSeq Integration v2.2.1 in February to support the S1 flow cell.
-     Releasing version 5.1 in Q1 2018 to improve workflow management.
-     Continuing development work to support the future evolutions of the NovaSeq instrument.
-     Starting the development of operations interface features (Lablink, Advanced search, Genealogy) in 2019.  This should enable existing customers to move from v4.x to a more secure version of the product.
-     After these features, there will be no new development on the stand-alone product.

**Comment by gaviriar** [comment]
Ok great thanks. If it turns out I need anything additional I will look into updating the source. 

FYI, i have a couple other questions will ask them in separate issue for traceability. Hope you dont mind.

**Comment by rich7409** [comment]
Hi. I've put the additions for 5.1/2.26 into the master branch. I've not tagged it yet. Bear in mind I'm flying blind with this as I don't have a Clarity 5.1 server to test against. The changes have been purely from the documentation and XSD files. I may have got something wrong, particularly with what the "PoolStep" class links to. It implies it links to a process step (/steps/XXXX end point) but I don't know for sure.

**Comment by gaviriar** [comment]
Hi Rich,

Thanks for making the update, I will test out and let you know if I face any issues. :+1:
