### ISSUE TITLE
delete/deleteAll does not work on LimsLink's

### ISSUE THREAD

**Issue by jeffrey-aguilera** [crukci-bioinformatics/clarityclient#8]
delete checks the passed entity's annotation to see that both @GenologicsEntity is present and removeable is true.  A LimsLink, e.g., ri.container.ContainerLink, does not have the @GenologicsEntity annotation ... but the item it refers to is deletable (without loading the entity.) 

The problem is that delete calls doDelete(entity.getUri, entity.getClass).  For LimsLink's, it should be calling entity.getEntityClass.

The current implementation requires loading a link and then deleting the reified object. Obviously, this is not desirable.

The proper solution would be to add the entityClass to the delete/deleteAll API call, like retrieve and load; or add an API entry point to deleteLink, deleteAllLinks that does the proper getEntityClass lookup.

**Comment by rich7409** [comment]
Well spotted. We delete things so rarely this has not come up, and when I have (mostly in tests against our development database that aren't in the Github project) we've already had the entity available to delete.

I've put a fix in to the master and clarity4 branches look at the type of Locatable passed in and, if it is an object that implements LimsLink, use the class returned by LimsLink.getEntityClass to perform the further tests (i.e. is it allowed to be deleted).

So you can now pass in actual entities or links to entities and it should work correctly for both. If using the deleteAll method, the collection still needs to be homogeneous: all entities of the same type or all links of the same type. That could be changed for delete only to do this same translation, but case for having a mix in there is small. In the end, there is no bulk delete so if it's a problem, one can write one's own loop to delete them one by one.

Thanks for bringing it up. I'll tag it and do a release build tomorrow.

Rich.

**Comment by rich7409** [comment]
Well spotted. We delete things so rarely this has not come up, and when I have (mostly in tests against our development database that aren't in the Github project) we've already had the entity available to delete.

I've put a fix in to the master and clarity4 branches look at the type of Locatable passed in and, if it is an object that implements LimsLink, use the class returned by LimsLink.getEntityClass to perform the further tests (i.e. is it allowed to be deleted).

So you can now pass in actual entities or links to entities and it should work correctly for both. If using the deleteAll method, the collection still needs to be homogeneous: all entities of the same type or all links of the same type. That could be changed for delete only to do this same translation, but case for having a mix in there is small. In the end, there is no bulk delete so if it's a problem, one can write one's own loop to delete them one by one.

Thanks for bringing it up. I'll tag it and do a release build tomorrow.

Rich.
